"""Added size column to uploads table

Revision ID: 17c32bd785e3
Revises: 591022583d54
Create Date: 2016-05-06 17:14:38.092821

"""

# revision identifiers, used by Alembic.
revision = '17c32bd785e3'
down_revision = '591022583d54'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('size', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'size')
    ### end Alembic commands ###
