"""added archived flag

Revision ID: 1de13fd625b1
Revises: 2fcf420c6c0c
Create Date: 2016-01-03 19:38:16.718453

"""

# revision identifiers, used by Alembic.
revision = "1de13fd625b1"
down_revision = "2fcf420c6c0c"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("samples", sa.Column("isarchived", sa.Boolean(), nullable=True))
    op.execute('UPDATE "samples" SET isarchived=0;')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("samples", "isarchived")
    ### end Alembic commands ###
