"""added path column to SMBRes

Revision ID: 2fcf420c6c0c
Revises: 449283d5217f
Create Date: 2016-01-03 17:39:38.250830

"""

# revision identifiers, used by Alembic.
revision = "2fcf420c6c0c"
down_revision = "449283d5217f"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("smbresources", sa.Column("path", sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("smbresources", "path")
    ### end Alembic commands ###
