"""added isdeleted flag to Sample

Revision ID: 3180b28651e3
Revises: cb354c75d49
Create Date: 2019-12-02 18:36:00.002075

"""

# revision identifiers, used by Alembic.
revision = '3180b28651e3'
down_revision = 'cb354c75d49'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('isdeleted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'isdeleted')
    ### end Alembic commands ###
