"""added extension column to uploads table

Revision ID: 365a26270961
Revises: a45942d815f
Create Date: 2016-03-07 12:08:24.950137

"""

# revision identifiers, used by Alembic.
revision = "365a26270961"
down_revision = "a45942d815f"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("uploads", sa.Column("ext", sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("uploads", "ext")
    ### end Alembic commands ###
