"""added sample description column

Revision ID: 449283d5217f
Revises: 578518528886
Create Date: 2015-12-31 16:22:34.708421

"""

# revision identifiers, used by Alembic.
revision = '449283d5217f'
down_revision = '578518528886'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('description', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'description')
    ### end Alembic commands ###
