"""initial migration

Revision ID: 4ca6d5b7b966
Revises: None
Create Date: 2015-12-15 22:34:42.521804

"""

# revision identifiers, used by Alembic.
revision = "4ca6d5b7b966"
down_revision = None

from alembic import op
import sqlalchemy as sa
from werkzeug.security import generate_password_hash


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actiontypes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "sampletypes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "smbresources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("servername", sa.String(length=64), nullable=True),
        sa.Column("serveraddr", sa.String(length=64), nullable=True),
        sa.Column("sharename", sa.String(length=64), nullable=True),
        sa.Column("userid", sa.String(length=64), nullable=True),
        sa.Column("password", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=64), nullable=True),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "samples",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("sampletype_id", sa.Integer(), nullable=True),
        sa.Column("image", sa.String(length=300), nullable=True),
        sa.Column("mwidth", sa.Integer(), nullable=True),
        sa.Column("mheight", sa.Integer(), nullable=True),
        sa.Column("mx", sa.Integer(), nullable=True),
        sa.Column("my", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["samples.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sampletype_id"],
            ["sampletypes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_samples_name"), "samples", ["name"], unique=True)
    op.create_table(
        "actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.Date(), nullable=True),
        sa.Column("sample_id", sa.Integer(), nullable=True),
        sa.Column("actiontype_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.UnicodeText(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actiontype_id"],
            ["actiontypes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sample_id"],
            ["samples.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shares",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sample_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sample_id"],
            ["samples.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ### end Alembic commands ###
    op.execute(
        """
        INSERT INTO "users"(email, username, password_hash, is_admin)
        VALUES ("admin@admin.com", "admin", "{}", 1);
        """.format(
            generate_password_hash("admin")
        )
    )


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shares")
    op.drop_table("actions")
    op.drop_index(op.f("ix_samples_name"), table_name="samples")
    op.drop_table("samples")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("smbresources")
    op.drop_table("sampletypes")
    op.drop_table("actiontypes")
    ### end Alembic commands ###
