"""added ordnum and datecreated to Action model

Revision ID: 50d1a487c7ab
Revises: 365a26270961
Create Date: 2016-04-17 14:26:15.814603

"""

# revision identifiers, used by Alembic.
revision = '50d1a487c7ab'
down_revision = '365a26270961'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('datecreated', sa.Date(), nullable=True))
    op.add_column('actions', sa.Column('ordnum', sa.Integer(), nullable=True))
    op.execute(
        'UPDATE "actions" SET ordnum=id;'
    )
    op.execute(
        'UPDATE "actions" SET datecreated=timestamp;'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actions', 'ordnum')
    op.drop_column('actions', 'datecreated')
    ### end Alembic commands ###
