"""Added ownership to actions

Revision ID: 578518528886
Revises: 4ca6d5b7b966
Create Date: 2015-12-31 11:12:41.459188

"""

# revision identifiers, used by Alembic.
revision = '578518528886'
down_revision = '4ca6d5b7b966'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions') as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('actions', 'users', ['owner_id'], ['id'])
    op.execute(
        'UPDATE "actions" SET owner_id=1;'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions') as batch_op:
        batch_op.drop_constraint('actions', type_='foreignkey')
        batch_op.drop_column('owner_id')
    ### end Alembic commands ###
