"""Added hash column to uploads table

Revision ID: 591022583d54
Revises: 50d1a487c7ab
Create Date: 2016-05-04 20:02:24.955367

"""

# revision identifiers, used by Alembic.
revision = "591022583d54"
down_revision = "50d1a487c7ab"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("uploads", sa.Column("hash", sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("uploads", "hash")
    ### end Alembic commands ###
