"""added last_modified field to sample model

Revision ID: 70dd6f0306c4
Revises: 3180b28651e3
Create Date: 2019-12-15 15:53:30.800517

"""

# revision identifiers, used by Alembic.
revision = "70dd6f0306c4"
down_revision = "3180b28651e3"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("samples", sa.Column("last_modified", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("samples", "last_modified")
    # ### end Alembic commands ###
