"""add user tokens

Revision ID: 71c1f7625171
Revises: 9c070b1a9f8b
Create Date: 2023-01-07 11:53:56.079100

"""

# revision identifiers, used by Alembic.
revision = "71c1f7625171"
down_revision = "9c070b1a9f8b"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("token", sa.String(length=32), nullable=True))
    op.add_column("users", sa.Column("token_expiration", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_users_token"), "users", ["token"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_token"), table_name="users")
    op.drop_column("users", "token_expiration")
    op.drop_column("users", "token")
    # ### end Alembic commands ###
