"""add collaborative sample flag

Revision ID: 86ec305ceaa7
Revises: 31fd4405fcd2
Create Date: 2020-08-29 11:33:59.747704

"""

# revision identifiers, used by Alembic.
revision = '86ec305ceaa7'
down_revision = '31fd4405fcd2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('iscollaborative', sa.Boolean(), nullable=True))
    op.execute(
        'UPDATE "samples" SET iscollaborative=0;'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'iscollaborative')
    # ### end Alembic commands ###
