"""added upload table

Revision ID: a45942d815f
Revises: 1de13fd625b1
Create Date: 2016-03-07 12:00:50.283535

"""

# revision identifiers, used by Alembic.
revision = "a45942d815f"
down_revision = "1de13fd625b1"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uploads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("uploads")
    ### end Alembic commands ###
