# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['run_app.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('../version.csv', '.'),
        ('../migrations', 'migrations'),
        ('../app/templates', 'app/templates'),
        ('../app/static', 'app/static'),
    ],
    hiddenimports=[
        # credit https://stackoverflow.com/a/77330257
        'celery.app.amqp',
        'celery.app.log',
        'celery.worker.autoscale',
        'celery.worker.components',
        'celery.bin',
        'celery.utils',
        'celery.utils.dispatch',
        'celery.contrib.testing',
        'celery.utils.static',
        'celery.concurrency.prefork',
        'celery.app.events',
        'celery.events.state',
        'celery.app.control',
        'celery.backends.redis',
        'celery.backends',
        'celery.backends.database',
        'celery.worker',
        'celery.worker.consumer',
        'celery.app',
        'celery.loaders',
        'celery.security',
        'celery.fixups',
        'celery.concurrency',
        'celery.events',
        'celery.contrib',
        'celery.apps',
        'celery',
        'celery.fixups',
        'celery.fixups.django',
        'celery.apps.worker',
        'celery.worker.strategy',
        'kombu.transport.redis',
        'sqlalchemy.sql.default_comparator',
        'sqlalchemy.ext.baked',
        # additionals
        'kombu.transport.pyamqp',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='run_app',
    debug=True,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='run_app',
)
